# to enable
# `pip install pre-commit && pre-commit install && pre-commit run --all-files`
# optional: pre-commit autoupdate
# OR https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories
# refs
# https://github.com/mCodingLLC/pre-commit-example-project/blob/master/.pre-commit-config.yaml
# https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-config.yaml
# https://github.com/google/yapf/blob/main/.pre-commit-config.yaml

repos:
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
        args: [--safe]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: sort-simple-yaml
        language_version: python3

# ---------------------------------------------------------------------------- #
#                                     shell                                    #
# ---------------------------------------------------------------------------- #

-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
    -   id: shellcheck
        args: ["--severity=error"]  # error/warning/info/disabled
        types: [shell]

# ---------------------------------------------------------------------------- #
#                                   markdown                                   #
# ---------------------------------------------------------------------------- #

# generate a table of contents for markdown files inside the repo
-   repo: https://github.com/thlorenz/doctoc
    rev: v2.1.0
    hooks:
    -   id: doctoc
        args: ["--title=Table of Contents","--maxlevel=1"]

# # conflict with doctoc
# -   repo: https://github.com/igorshubovych/markdownlint-cli
#     rev: v0.31.0
#     hooks:
#     -   id: markdownlint
#         types: [markdown]

# ---------------------------------------------------------------------------- #
#                                    docker                                    #
# ---------------------------------------------------------------------------- #

-   repo: https://github.com/hadolint/hadolint
    rev: master
    hooks:
      - id: hadolint-docker

# ---------------------------------------------------------------------------- #
#                                python-related                                #
# ---------------------------------------------------------------------------- #

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        files: ^src/

# ---------------------------------------------------------------------------- #
#                                   R-related                                  #
# ---------------------------------------------------------------------------- #

-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.2
    hooks:
    -   id: style-files
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    -   id: roxygenize
    -   id: use-tidy-description
    -   id: lintr
        args: [--warn_only]
