# to enable
# `pip install pre-commit && pre-commit install && pre-commit run --all-files`
# optional: pre-commit autoupdate
# OR https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories
# set up pre-commit for hooks that require system-level dependencies
# https://github.com/openproblems-bio/openproblems/blob/main/.github/workflows/pre-commit.yml

repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--safe]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
        exclude: CMU_15213
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: sort-simple-yaml
        language_version: python3

# ---------------------------------------------------------------------------- #
#                                     shell                                    #
# ---------------------------------------------------------------------------- #

-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
    -   id: shellcheck
        args: ["--severity=error"]  # error/warning/info/disabled
        types: [shell]

# ---------------------------------------------------------------------------- #
#                                   markdown                                   #
# ---------------------------------------------------------------------------- #

# generate a table of contents for markdown files inside the repo
-   repo: https://github.com/thlorenz/doctoc
    rev: v2.1.0
    hooks:
    -   id: doctoc
        args: ["--maxlevel=1","--notitle"]
        # args: ["--title=Table of Contents","--maxlevel=1"]

# # conflict with doctoc
# -   repo: https://github.com/igorshubovych/markdownlint-cli
#     rev: v0.31.0
#     hooks:
#     -   id: markdownlint
#         types: [markdown]

# ---------------------------------------------------------------------------- #
#                                    docker                                    #
# ---------------------------------------------------------------------------- #

# -   repo: https://github.com/hadolint/hadolint
#     rev: v2.10.0
#     hooks:
#       - id: hadolint-docker

# ---------------------------------------------------------------------------- #
#                                python-related                                #
# ---------------------------------------------------------------------------- #

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        files: ^src/

# ---------------------------------------------------------------------------- #
#                                   R-related                                  #
# ---------------------------------------------------------------------------- #

# require R installed (system-dependencies)
# -   repo: https://github.com/lorenzwalthert/precommit
#     rev: v0.2.2.9013
#     hooks:
#     -   id: style-files
#         language: r
#     -   id: parsable-R
#         language: r
#     -   id: no-browser-statement
#         language: r
#     -   id: readme-rmd-rendered
#         language: r
#     -   id: roxygenize
#         language: r
#     -   id: use-tidy-description
#         language: r
#     -   id: lintr
#         args: [--warn_only]
#         language: r
